{{- if .Values.ingress.enabled }}
{{- $fullName := include "byceps.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
---
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else -}}    
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "byceps.fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
  labels:
    {{- include "byceps.labels" . | nindent 4 }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range $ingressExtraPaths }}
      - path: {{ default "/" .path | quote }}
        backend:
          service:
            name: {{ $fullName }}-service
            port:
              number: {{ $svcPort }}
        pathType: Prefix
      {{- end }}
      - path: {{ default "/" .path | quote }}
        backend:
          service:
            name: {{ $fullName }}-service
            port:
              number: {{ $svcPort }}
        pathType: Prefix
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end -}}