apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "byceps.fullname" . }}-pvc
  namespace: {{ template "byceps.namespace" . }}
  labels:
    {{- include "byceps.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass }}