apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ template "byceps.namespace" . }}
  labels:
    {{- include "byceps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: admin
      port: 81
      targetPort: 81
      protocol: TCP
    - name: site
      port: 82
      targetPort: 82
      protocol: TCP
  selector:
    {{- include "byceps.selectorLabels" . | nindent 4 }}
